### ISSUE TITLE
What is "main folder"?

### ISSUE THREAD

**Issue by ghost** [lephong/mulrel-nel#1]
I read README.md, but I don't know what "main folder" is.

Which is the "main folder", https://github.com/lephong/mulrel-nel or https://github.com/lephong/mulrel-nel/tree/master/nel ?

**Comment by sugiyamath** [comment]
Maybe, I understand which is the correct one.
According to README.md, it shows this command:

`python -u -m nel.main --mode train --n_rels 3 --mulrel_type ment-norm --model_path model
`

and, if we can run it by "nel.main", the main folder is https://github.com/lephong/mulrel-nel because if not, it should be just "main".

**Comment by lephong** [comment]
Thanks for pointing out that. The main folder in this case is your-folder/mulrel-nel. I will write it clearer in README.md
