### ISSUE TITLE
how to use the model on new data?

### ISSUE THREAD

**Issue by leolle** [lephong/mulrel-nel#4]
Hi, how can I modify this code to use it on new raw text data if I want to recognize entities and ground truth entity?
Thank you.

**Comment by lephong** [comment]
Unfortunately, the souce code doesn't include a part for handling raw data. You have to convert your raw text into the format of the train/test files. To do so, you have to do two steps:
- NER your text (using e.g. Standford CORENLP, SpiCy)
- then use the source code from https://github.com/dalab/deep-ed to convert to the correct format. But, you need to modify it a little bit. 

Our next version will include a piece of sorce code to do that. But you have to wait, maybe some months.

**Comment by leolle** [comment]
I am looking forward it coming out early.

**Comment by LMY-nlp0701** [comment]
I am looking forward it coming out early.
thank you so much!

**Comment by LearningPytorch** [comment]
Is there any update to produce the source code to format raw text as input? It'll be very helpful for other datasets. TIA

**Comment by shirakad** [comment]
Hi, 
Is it possible now to use the model on new data?
Thanks

**Comment by lephong** [comment]
It should be straightforward to apply the model on new data. Unfortunately, sorry, I have no time to do that. (This is only for replicating the results in the paper.)

**Comment by iuria21** [comment]
Hi for all. First thanks @lephong for your work. I have a short question and maybe someone could help me:

I'm creating a new dataset, I have data with labeled NER and links to each Entity. I could create a dataset like (instead of Wikipedia link I have a link to a law-code):

```
As 
we
saw 
in 
the 
Mortgage   B           LJ/2006/172
Law        I           LJ/2006/172
...
```

Can I train a model with this data or do I need something else? There are some columns in `aida_train.txt` that I don't know what are them. And is the model taking the all possible link set from the training set or is it somewhere? And will the entity embeddings be useful for this case?

Thanks!!
