### ISSUE TITLE
questions on Ment-norm model

### ISSUE THREAD

**Issue by futaoo** [lephong/mulrel-nel#9]
I am just digging in your thesis, but I am a little uncertain about the mechanism of ment-norm model. As there should be one case that multiple mentions may have the same relation k with the mention (assume this to be mi) currently considered, will the mi tend to consider all those the mentions equally or assign different weight to those mentions?

**Comment by lephong** [comment]
You were right about that. For each relation r_k, in theory, m_i can choose only one m_j. However, there are two points: (1) r_k and r_h can be similar, so m_i can choose more than one m_j for a relation. Of course we encorage that relations are different from each other by adding a regularization term to the loss, but the model can equalize some relations if needed. (2) Because our purpose is entity linking, not relation extraction, for each m_i, we need only one m_j that supports m_i under relation r_k. Therefore, we don't think that m_i need more than one m_j. But of course, we would like to model that so our approach can be used for both entity linking and relation extraction. Any ideas are welcome.
